# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jaccard_coeff_parallel <- function(idx) {
    .Call('_Rphenoannoy_jaccard_coeff_parallel', PACKAGE = 'Rphenoannoy', idx)
}

jaccard_coeff <- function(idx) {
    .Call('_Rphenoannoy_jaccard_coeff', PACKAGE = 'Rphenoannoy', idx)
}

jaccard_coeff_true_parallel <- function(idx) {
    .Call('_Rphenoannoy_jaccard_coeff_true_parallel', PACKAGE = 'Rphenoannoy', idx)
}

knn_annoy <- function(mat, K = 100L, trees = 150L) {
    .Call('_Rphenoannoy_knn_annoy', PACKAGE = 'Rphenoannoy', mat, K, trees)
}

